[pytest]
# 1. 터미널 실행 시 기본 옵션
addopts = -v --strict-markers

# 2. 실시간 로그 활성화
log_cli = true

# 3. 로그 레벨 및 포맷 설정
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

# 4. 파일로도 저장하고 싶을 때
log_file = part1_api_automation/logs/pytest.log
log_file_level = DEBUG
log_file_format = %(asctime)s [%(levelname)s] %(message)s